### ISSUE TITLE
The success check in the script doesn't seem to be a valid check to see if slots are open

### ISSUE THREAD

**Issue by rushi** [LeninGangwal/Big-Basket-Delivery-Slots#3]
This particular line in the code doesn't seem to be a good check to see if slots are available https://github.com/LeninGangwal/Big-Basket-Delivery-Slots/blob/0e2a5c3420f64c315d74c2133dd04aeddbf56bf0/BB_slot.py#L25

I've been running this script for a while, and finally the page redirected to https://www.bigbasket.com/co/checkout/?x=0&spni=21&addr=someid which according to the code indicates that slots are open, but the page instead showed this error:

![Screenshot 2020-04-10 at 17 46 49](https://user-images.githubusercontent.com/65708/78998561-85ce6c80-7b66-11ea-8820-d463cbddae76.jpg)

So this `if` condition doesn't seem to work. Is there a better check that can be done? I haven't had a successful order on Big basket so I don't what a good check would be.

**Comment by LeninGangwal** [comment]
You are right! I added the fix for that. Thanks for pointing it out.

**Comment by rushi** [comment]
Hi again @LeninGangwal,

I pulled the latest changes, and this particular line doesn't seem todo the trick.

https://github.com/LeninGangwal/Big-Basket-Delivery-Slots/blob/c369655caff86a05b659e113541efae7f05b9cdd/BB_slot.py#L27

Here's a screenshot from my system showing the Bigbasket website and script output side-by-side

<img width="1890" alt="Big_Basket_Delivery_Slots" src="https://user-images.githubusercontent.com/65708/79042424-69d5d400-7c15-11ea-905c-5f0d737274c0.png">

I'm going to dig around and try to find a fix, but Python isn't my cup of tea, so any help would be appreciated.

**Comment by LeninGangwal** [comment]
Hmm got it. This should not happen ideally unless your internet is quite slow and the popup loads up after the 5 sec sleep time.
I 'll try to update the script, but for now, you can try increasing the sleep time to say 15 seconds maybe.
`time.sleep(5)  #driver take a few secs to update the new URL`

**Comment by rushi** [comment]
Ok I've bumped that to 45 seconds to give it plenty of time. I'll keep the script running and get back to you

**Comment by rushi** [comment]
After some trial and error a sleep of 20 seconds did the trick. No failures so far, and I finally got a slot 🎉

**Comment by LeninGangwal** [comment]
Greaat 👍
